apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle
  namespace: oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      securityContext:
        fsGroup: 54321
      containers:
        - name: oracle
          image: container-registry.oracle.com/database/free:23.3.0.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: oracle-common
            # - configMapRef:
            #     name: oracle
          env:
            - name: ORACLE_PWD
              valueFrom:
                secretKeyRef:
                  name: oracle
                  key: password
          volumeMounts:
            - mountPath: "/opt/oracle/oradata"
              name: oracle
      volumes:
        - name: oracle
          persistentVolumeClaim:
            claimName: oracle
  volumeClaimTemplates:
    - metadata:
        name: oracle
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 12Gi
---
apiVersion: v1
kind: Service
metadata:
  name: oracle
  namespace: oracle
spec:
  type: LoadBalancer
  ports:
    - name: oraclenet
      port: 1521
      targetPort: 1521
    - name: em
      port: 5500
      targetPort: 5500
      protocol: TCP
  selector:
    app: oracle
