apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ords
  namespace: oracle
data: # Default value is "CONN_STRING=sys/oracle@oracle:1521/FREEPDB1". If you change DB password,you must change it.
  conn_string: Q09OTl9TVFJJTkc9c3lzL29yYWNsZUBvcmFjbGU6MTUyMS9GUkVFUERCMQ==
